### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Cons-Cat** [SuperV1234/bcs_thesis#3]
(I read the web pdf version)
In section ``4.1.4.2 Inner parallelism``, the first sentence reads
"Other **that** running separate systems in parallel,"

I think this is intended to be
"Other **than** running separate systems in parallel,"

This is a great paper!

**Comment by vittorioromeo** [comment]
Glad you like the paper! I fixed the typo in the source material, but have no time at the moment to recompile the PDF version and reupload :)
